version: "3.9"

services:
  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    environment:
      BASE_URL: ${BASE_URL}
      API_ROUTE: ${API_ROUTE}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - web

  web:
    image: dew-web
    build:
      context: web
      args:
        VITE_API_URL: ${BASE_URL}${API_ROUTE}
    networks:
      - proxy
    depends_on:
      - backend

  backend:
    image: dew-backend
    build:
      context: backend
    networks:
      - proxy
      - db
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../data:/data/db
    networks:
      - db

networks:
  proxy:
  db:
