name: Lint, test, and build backend
on:
  push:
    branches: ["**"]
    paths: ["backend"]
jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint with gofmt
        run: test -z "$(gofmt -l .)"
      - name: Test with go
        run: go test
