name: Lint, test, and build web
on:
  push:
    branches: ["**"]
    paths: ["web"]
jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true
      - name: Lint with Prettier
        run: pnpm run lint
      - name: Test with Jest
        run: pnpm run test
      - name: Build with pnpm
        run: pnpm run build
